server:
  port: 8000
#security:
#  oauth2:
#    client:
#      client-id: test
#      client-secret: test1234
#      registered-redirect-uri: http://www.baidu.com
spring:
  application:
    name: oauth2-server   # 应用名称

  thymeleaf:
    prefix: classpath:/templates/

logging:
  level:
    org.springframework.security: DEBUG
